import translations from "@/constants/Translations";
import type { Language } from "@/contexts/LanguageContext";

export type DictionaryItem = {
  name: string;
  name_norm: string;
  desc: string;
  example: string;
};

type RawDictionaryRecord = {
  category: string;
  lang: "id" | "fr";
  seq_no: number;
  term: string;
  term_norm: string;
  definition: string;
  def_citation: string;
  ex_source: string;
  ex_date: string;
  ex_quote: string;
  ex_analysis: string;
};

export const Data: RawDictionaryRecord[] = [
  {
    category: "Analisis Wacana",
    lang: "id",
    seq_no: 1,
    term: "ACD",
    term_norm: "acd",
    definition: "Analisis hubungan bahasa dan kekuasaan dalam wacana.",
    def_citation: "Fairclough (1995)",
    ex_source: "Kompas",
    ex_date: "2023-01-10",
    ex_quote: "Kebijakan ini dianggap tidak adil.",
    ex_analysis: "Wacana kritik terhadap pemerintah.",
  },
  {
    category: "Analisis Wacana",
    lang: "id",
    seq_no: 2,
    term: "Agenda media",
    term_norm: "agenda media",
    definition: "Penentuan isu utama oleh media.",
    def_citation: "McCombs (2004)",
    ex_source: "Tempo",
    ex_date: "2023-02-01",
    ex_quote: "Isu ekonomi mendominasi berita.",
    ex_analysis: "Prioritisasi isu ekonomi.",
  },
  {
    category: "Analisis Wacana",
    lang: "id",
    seq_no: 3,
    term: "Agentivitas",
    term_norm: "agentivitas",
    definition: "Tingkat kehadiran agen dalam kalimat.",
    def_citation: "van Leeuwen (2008)",
    ex_source: "Detik",
    ex_date: "2023-03-01",
    ex_quote: "Terjadi penangkapan massal.",
    ex_analysis: "Agen dihilangkan.",
  },
  {
    category: "Analisis Wacana",
    lang: "id",
    seq_no: 4,
    term: "Pasivasi",
    term_norm: "pasivasi",
    definition: "Penggunaan bentuk pasif untuk mengaburkan agen.",
    def_citation: "van Leeuwen (2008)",
    ex_source: "CNN Indonesia",
    ex_date: "2023-03-15",
    ex_quote: "Demonstran dibubarkan.",
    ex_analysis: "Agen tidak disebutkan.",
  },
  {
    category: "Analisis Wacana",
    lang: "id",
    seq_no: 5,
    term: "Alterisasi",
    term_norm: "alterisasi",
    definition: "Pembentukan oposisi sosial.",
    def_citation: "van Dijk (1998)",
    ex_source: "Media Indonesia",
    ex_date: "2023-04-01",
    ex_quote: "Mereka bukan bagian dari kita.",
    ex_analysis: "Polarisasi kelompok.",
  },
  {
    category: "Analisis Wacana",
    lang: "id",
    seq_no: 6,
    term: "Hegemoni",
    term_norm: "hegemoni",
    definition: "Dominasi ideologis yang diterima sebagai wajar.",
    def_citation: "Gramsci (1971)",
    ex_source: "Kompas",
    ex_date: "2023-05-10",
    ex_quote: "Kebijakan itu dianggap demi kepentingan bersama.",
    ex_analysis: "Dominasi diterima sebagai kewajaran.",
  },
  {
    category: "Analisis Wacana",
    lang: "id",
    seq_no: 7,
    term: "Intertekstualitas",
    term_norm: "intertekstualitas",
    definition: "Keterkaitan teks dengan teks lain.",
    def_citation: "Kristeva (1980)",
    ex_source: "Tempo",
    ex_date: "2023-05-12",
    ex_quote: "Pernyataan itu mengulang slogan lama.",
    ex_analysis: "Rujukan pada wacana sebelumnya.",
  },
  {
    category: "Analisis Wacana",
    lang: "id",
    seq_no: 8,
    term: "Framing",
    term_norm: "framing",
    definition: "Cara media membingkai isu.",
    def_citation: "Entman (1993)",
    ex_source: "CNN Indonesia",
    ex_date: "2023-05-15",
    ex_quote: "Isu itu disebut krisis nasional.",
    ex_analysis: "Aspek tertentu ditegaskan.",
  },
  {
    category: "Analisis Wacana",
    lang: "id",
    seq_no: 9,
    term: "Ideologi",
    term_norm: "ideologi",
    definition: "Sistem nilai yang membimbing representasi.",
    def_citation: "van Dijk (1998)",
    ex_source: "Media Indonesia",
    ex_date: "2023-05-18",
    ex_quote: "Kita harus menjaga tatanan.",
    ex_analysis: "Nilai dominan diarahkan.",
  },
  {
    category: "Analisis Wacana",
    lang: "id",
    seq_no: 10,
    term: "Legitimasi",
    term_norm: "legitimasi",
    definition: "Strategi pembenaran tindakan atau kebijakan.",
    def_citation: "van Leeuwen (2008)",
    ex_source: "Kompas",
    ex_date: "2023-05-20",
    ex_quote: "Program ini sesuai amanat rakyat.",
    ex_analysis: "Pembenaran lewat otoritas.",
  },
  {
    category: "Analisis Wacana",
    lang: "id",
    seq_no: 11,
    term: "Delegitimasi",
    term_norm: "delegitimasi",
    definition: "Strategi melemahkan otoritas pihak lain.",
    def_citation: "van Leeuwen (2008)",
    ex_source: "Detik",
    ex_date: "2023-05-22",
    ex_quote: "Kebijakan itu dianggap tidak sah.",
    ex_analysis: "Otoritas dilemahkan.",
  },
  {
    category: "Analisis Wacana",
    lang: "id",
    seq_no: 12,
    term: "Nominalisasi",
    term_norm: "nominalisasi",
    definition: "Pengubahan verba menjadi nomina untuk menutup agen.",
    def_citation: "Halliday (1994)",
    ex_source: "Tempo",
    ex_date: "2023-05-24",
    ex_quote: "Terjadi penertiban.",
    ex_analysis: "Agen disamarkan.",
  },
  {
    category: "Analisis Wacana",
    lang: "id",
    seq_no: 13,
    term: "Modalitas",
    term_norm: "modalitas",
    definition: "Sikap penutur terhadap kebenaran atau keharusan.",
    def_citation: "Fairclough (1992)",
    ex_source: "Kompas",
    ex_date: "2023-05-26",
    ex_quote: "Pemerintah harus bertindak.",
    ex_analysis: "Keharusan ditekankan.",
  },
  {
    category: "Analisis Wacana",
    lang: "id",
    seq_no: 14,
    term: "Evaluasi",
    term_norm: "evaluasi",
    definition: "Penilaian sikap terhadap peristiwa.",
    def_citation: "Martin & White (2005)",
    ex_source: "CNN Indonesia",
    ex_date: "2023-05-28",
    ex_quote: "Langkah itu sangat berani.",
    ex_analysis: "Sikap positif ditonjolkan.",
  },
  {
    category: "Analisis Wacana",
    lang: "id",
    seq_no: 15,
    term: "Topikalisasi",
    term_norm: "topikalisasi",
    definition: "Pemilihan topik untuk menonjolkan informasi tertentu.",
    def_citation: "Brown & Yule (1983)",
    ex_source: "Media Indonesia",
    ex_date: "2023-05-30",
    ex_quote: "Soal harga, pemerintah memberi jaminan.",
    ex_analysis: "Topik diposisikan di depan.",
  },
  {
    category: "Analisis Wacana",
    lang: "fr",
    seq_no: 6,
    term: "ACD",
    term_norm: "acd",
    definition: "Analyse critique du discours et du pouvoir.",
    def_citation: "Fairclough (1995)",
    ex_source: "Le Monde",
    ex_date: "2023-01-10",
    ex_quote: "La réforme est injuste.",
    ex_analysis: "Discours critique.",
  },
  {
    category: "Analisis Wacana",
    lang: "fr",
    seq_no: 7,
    term: "Agenda médiatique",
    term_norm: "agenda mediatique",
    definition: "Priorités définies par les médias.",
    def_citation: "McCombs (2004)",
    ex_source: "Le Figaro",
    ex_date: "2023-02-01",
    ex_quote: "L’économie domine l’actualité.",
    ex_analysis: "Hiérarchisation des sujets.",
  },
  {
    category: "Analisis Wacana",
    lang: "fr",
    seq_no: 8,
    term: "Agentivité",
    term_norm: "agentivite",
    definition: "Présence de l’agent dans l’énoncé.",
    def_citation: "van Leeuwen (2008)",
    ex_source: "France24",
    ex_date: "2023-03-01",
    ex_quote: "Il y a eu arrestation.",
    ex_analysis: "Agent absent.",
  },
  {
    category: "Analisis Wacana",
    lang: "fr",
    seq_no: 9,
    term: "Passivation",
    term_norm: "passivation",
    definition: "Usage du passif pour masquer l’agent.",
    def_citation: "van Leeuwen (2008)",
    ex_source: "BFM TV",
    ex_date: "2023-03-15",
    ex_quote: "Les manifestants ont été dispersés.",
    ex_analysis: "Agent implicite.",
  },
  {
    category: "Analisis Wacana",
    lang: "fr",
    seq_no: 10,
    term: "Altérisation",
    term_norm: "alterisation",
    definition: "Construction de l’opposition sociale.",
    def_citation: "van Dijk (1998)",
    ex_source: "Le Figaro",
    ex_date: "2023-04-01",
    ex_quote: "Ils ne sont pas comme nous.",
    ex_analysis: "Polarisation.",
  },
  {
    category: "Analisis Wacana",
    lang: "fr",
    seq_no: 11,
    term: "Hégémonie",
    term_norm: "hegemonie",
    definition: "Domination ideologique percue comme naturelle.",
    def_citation: "Gramsci (1971)",
    ex_source: "Le Monde",
    ex_date: "2023-05-10",
    ex_quote: "La mesure est presentee comme normale.",
    ex_analysis: "Acceptation de la domination.",
  },
  {
    category: "Analisis Wacana",
    lang: "fr",
    seq_no: 12,
    term: "Intertextualité",
    term_norm: "intertextualite",
    definition: "Relation d'un texte avec d'autres textes.",
    def_citation: "Kristeva (1980)",
    ex_source: "Le Figaro",
    ex_date: "2023-05-12",
    ex_quote: "Le discours reprend un slogan ancien.",
    ex_analysis: "Renvoi a un texte precedent.",
  },
  {
    category: "Analisis Wacana",
    lang: "fr",
    seq_no: 13,
    term: "Cadrage",
    term_norm: "cadrage",
    definition: "Maniere de cadrer un enjeu mediatiquement.",
    def_citation: "Entman (1993)",
    ex_source: "France24",
    ex_date: "2023-05-15",
    ex_quote: "Le sujet est traite comme une crise.",
    ex_analysis: "Mise en avant d'un angle.",
  },
  {
    category: "Analisis Wacana",
    lang: "fr",
    seq_no: 14,
    term: "Idéologie",
    term_norm: "ideologie",
    definition: "Systeme de valeurs qui guide la representation.",
    def_citation: "van Dijk (1998)",
    ex_source: "Le Monde",
    ex_date: "2023-05-18",
    ex_quote: "L'ordre social doit etre protege.",
    ex_analysis: "Valeurs dominantes.",
  },
  {
    category: "Analisis Wacana",
    lang: "fr",
    seq_no: 15,
    term: "Légitimation",
    term_norm: "legitimation",
    definition: "Strategies de justification d'une action.",
    def_citation: "van Leeuwen (2008)",
    ex_source: "Le Figaro",
    ex_date: "2023-05-20",
    ex_quote: "La reforme est conforme a la loi.",
    ex_analysis: "Justification par l'autorite.",
  },
  {
    category: "Analisis Wacana",
    lang: "fr",
    seq_no: 16,
    term: "Délégitimation",
    term_norm: "delegitimation",
    definition: "Strategies pour affaiblir l'autorite adverse.",
    def_citation: "van Leeuwen (2008)",
    ex_source: "BFM TV",
    ex_date: "2023-05-22",
    ex_quote: "La decision est declaree illegitime.",
    ex_analysis: "Affaiblissement de l'autorite.",
  },
  {
    category: "Analisis Wacana",
    lang: "fr",
    seq_no: 17,
    term: "Nominalisation",
    term_norm: "nominalisation",
    definition: "Transformation d'un verbe en nom pour effacer l'agent.",
    def_citation: "Halliday (1994)",
    ex_source: "Le Monde",
    ex_date: "2023-05-24",
    ex_quote: "Il y a eu expulsion.",
    ex_analysis: "Agent non mentionne.",
  },
  {
    category: "Analisis Wacana",
    lang: "fr",
    seq_no: 18,
    term: "Modalité",
    term_norm: "modalite",
    definition: "Attitude du locuteur envers la necessite ou la verite.",
    def_citation: "Fairclough (1992)",
    ex_source: "France24",
    ex_date: "2023-05-26",
    ex_quote: "Le gouvernement doit agir.",
    ex_analysis: "Necessite exprimee.",
  },
  {
    category: "Analisis Wacana",
    lang: "fr",
    seq_no: 19,
    term: "Évaluation",
    term_norm: "evaluation",
    definition: "Jugement attitudinal dans le discours.",
    def_citation: "Martin & White (2005)",
    ex_source: "Le Figaro",
    ex_date: "2023-05-28",
    ex_quote: "La mesure est courageuse.",
    ex_analysis: "Evaluation positive.",
  },
  {
    category: "Analisis Wacana",
    lang: "fr",
    seq_no: 20,
    term: "Topicalisation",
    term_norm: "topicalisation",
    definition: "Mise en avant d'un element comme topic.",
    def_citation: "Brown & Yule (1983)",
    ex_source: "Le Monde",
    ex_date: "2023-05-30",
    ex_quote: "Quant aux prix, l'Etat reagit.",
    ex_analysis: "Topique place en tete.",
  },

  {
    category: "Fonologi",
    lang: "id",
    seq_no: 1,
    term: "Fonem",
    term_norm: "fonem",
    definition: "Unit bunyi terkecil pembeda makna.",
    def_citation: "Sumber umum",
    ex_source: "Buku Linguistik",
    ex_date: "2020",
    ex_quote: "/p/ vs /b/",
    ex_analysis: "Perbedaan makna.",
  },
  {
    category: "Fonologi",
    lang: "id",
    seq_no: 2,
    term: "Alomorf",
    term_norm: "alomorf",
    definition: "Variasi bunyi morfem.",
    def_citation: "Referensi umum",
    ex_source: "Buku",
    ex_date: "2020",
    ex_quote: "meN-",
    ex_analysis: "Varian fonologis.",
  },
  {
    category: "Fonologi",
    lang: "id",
    seq_no: 3,
    term: "Suku kata",
    term_norm: "suku kata",
    definition: "Unit ritmis dalam ujaran.",
    def_citation: "Rujukan dasar",
    ex_source: "Buku",
    ex_date: "2020",
    ex_quote: "ba-ta",
    ex_analysis: "Dua suku kata.",
  },
  {
    category: "Fonologi",
    lang: "id",
    seq_no: 4,
    term: "Intonasi",
    term_norm: "intonasi",
    definition: "Variasi nada dalam ujaran.",
    def_citation: "Kajian umum",
    ex_source: "Buku",
    ex_date: "2020",
    ex_quote: "Kalimat tanya naik.",
    ex_analysis: "Fungsi pragmatis.",
  },
  {
    category: "Fonologi",
    lang: "id",
    seq_no: 5,
    term: "Asimilasi",
    term_norm: "asimilasi",
    definition: "Perubahan bunyi karena lingkungan.",
    def_citation: "Catatan umum",
    ex_source: "Buku",
    ex_date: "2020",
    ex_quote: "input → imput",
    ex_analysis: "Pengaruh bunyi.",
  },
  {
    category: "Fonologi",
    lang: "id",
    seq_no: 6,
    term: "Vokal",
    term_norm: "vokal",
    definition: "Bunyi ujaran tanpa hambatan berarti pada aliran udara.",
    def_citation: "Ladefoged (2001)",
    ex_source: "Buku Fonetik",
    ex_date: "2020",
    ex_quote: "a, i, u",
    ex_analysis: "Contoh vokal dasar.",
  },
  {
    category: "Fonologi",
    lang: "id",
    seq_no: 7,
    term: "Konsonan",
    term_norm: "konsonan",
    definition: "Bunyi dengan hambatan pada saluran vokal.",
    def_citation: "Ladefoged (2001)",
    ex_source: "Buku Fonetik",
    ex_date: "2020",
    ex_quote: "p, t, k",
    ex_analysis: "Ada hambatan artikulatoris.",
  },
  {
    category: "Fonologi",
    lang: "id",
    seq_no: 8,
    term: "Diftong",
    term_norm: "diftong",
    definition: "Gabungan dua vokal dalam satu suku kata.",
    def_citation: "Roach (2009)",
    ex_source: "Buku",
    ex_date: "2020",
    ex_quote: "ai pada kata pantai",
    ex_analysis: "Pergerakan vokal.",
  },
  {
    category: "Fonologi",
    lang: "id",
    seq_no: 9,
    term: "Nasalisasi",
    term_norm: "nasalisasi",
    definition: "Penambahan ciri nasal pada bunyi.",
    def_citation: "Crystal (2008)",
    ex_source: "Buku",
    ex_date: "2020",
    ex_quote: "vokal menjadi nasal",
    ex_analysis: "Udara keluar lewat hidung.",
  },
  {
    category: "Fonologi",
    lang: "id",
    seq_no: 10,
    term: "Aspirasi",
    term_norm: "aspirasi",
    definition: "Hembusan udara setelah letup.",
    def_citation: "Roach (2009)",
    ex_source: "Buku",
    ex_date: "2020",
    ex_quote: "p berhembus dalam bahasa Inggris",
    ex_analysis: "Hembusan terdengar.",
  },
  {
    category: "Fonologi",
    lang: "id",
    seq_no: 11,
    term: "Lenisi",
    term_norm: "lenisi",
    definition: "Pelemahan artikulasi bunyi.",
    def_citation: "Hyman (1975)",
    ex_source: "Buku",
    ex_date: "2020",
    ex_quote: "t menjadi d",
    ex_analysis: "Kekuatan bunyi menurun.",
  },
  {
    category: "Fonologi",
    lang: "id",
    seq_no: 12,
    term: "Fortisi",
    term_norm: "fortisi",
    definition: "Penguatan artikulasi bunyi.",
    def_citation: "Hyman (1975)",
    ex_source: "Buku",
    ex_date: "2020",
    ex_quote: "s menjadi t",
    ex_analysis: "Kekuatan bunyi meningkat.",
  },
  {
    category: "Fonologi",
    lang: "id",
    seq_no: 13,
    term: "Metatesis",
    term_norm: "metatesis",
    definition: "Pertukaran posisi bunyi dalam kata.",
    def_citation: "Campbell (2004)",
    ex_source: "Buku",
    ex_date: "2020",
    ex_quote: "krabu menjadi karbu",
    ex_analysis: "Pertukaran segmen.",
  },
  {
    category: "Fonologi",
    lang: "id",
    seq_no: 14,
    term: "Elisi",
    term_norm: "elisi",
    definition: "Penghilangan bunyi dalam ujaran.",
    def_citation: "Crystal (2008)",
    ex_source: "Buku",
    ex_date: "2020",
    ex_quote: "tidak menjadi gak",
    ex_analysis: "Bunyi hilang.",
  },
  {
    category: "Fonologi",
    lang: "id",
    seq_no: 15,
    term: "Harmoni vokal",
    term_norm: "harmoni vokal",
    definition: "Keseragaman ciri vokal dalam satu kata.",
    def_citation: "Katamba (1989)",
    ex_source: "Buku",
    ex_date: "2020",
    ex_quote: "vokal depan mendominasi",
    ex_analysis: "Penyelarasan vokal.",
  },
  {
    category: "Fonologi",
    lang: "fr",
    seq_no: 6,
    term: "Phonème",
    term_norm: "phoneme",
    definition: "Unité sonore distinctive.",
    def_citation: "Reference generale",
    ex_source: "Manuel",
    ex_date: "2020",
    ex_quote: "/p/ vs /b/",
    ex_analysis: "Différence de sens.",
  },
  {
    category: "Fonologi",
    lang: "fr",
    seq_no: 7,
    term: "Allomorphe",
    term_norm: "allomorphe",
    definition: "Variation phonétique d’un morphème.",
    def_citation: "Source generale",
    ex_source: "Manuel",
    ex_date: "2020",
    ex_quote: "in-/im-",
    ex_analysis: "Variation contextuelle.",
  },
  {
    category: "Fonologi",
    lang: "fr",
    seq_no: 8,
    term: "Syllabe",
    term_norm: "syllabe",
    definition: "Unité rythmique de la parole.",
    def_citation: "Note generale",
    ex_source: "Manuel",
    ex_date: "2020",
    ex_quote: "pa-ris",
    ex_analysis: "Deux syllabes.",
  },
  {
    category: "Fonologi",
    lang: "fr",
    seq_no: 9,
    term: "Intonation",
    term_norm: "intonation",
    definition: "Variation mélodique.",
    def_citation: "Reference standard",
    ex_source: "Manuel",
    ex_date: "2020",
    ex_quote: "Phrase interrogative montante.",
    ex_analysis: "Fonction communicative.",
  },
  {
    category: "Fonologi",
    lang: "fr",
    seq_no: 10,
    term: "Assimilation",
    term_norm: "assimilation",
    definition: "Modification phonétique par contexte.",
    def_citation: "Etude generale",
    ex_source: "Manuel",
    ex_date: "2020",
    ex_quote: "inpossible → impossible",
    ex_analysis: "Influence phonétique.",
  },
  {
    category: "Fonologi",
    lang: "fr",
    seq_no: 11,
    term: "Voyelle",
    term_norm: "voyelle",
    definition: "Son produit sans obstruction notable.",
    def_citation: "Ladefoged (2001)",
    ex_source: "Manuel de phonétique",
    ex_date: "2020",
    ex_quote: "a, i, u",
    ex_analysis: "Exemples de voyelles.",
  },
  {
    category: "Fonologi",
    lang: "fr",
    seq_no: 12,
    term: "Consonne",
    term_norm: "consonne",
    definition: "Son avec obstruction du conduit vocal.",
    def_citation: "Ladefoged (2001)",
    ex_source: "Manuel de phonétique",
    ex_date: "2020",
    ex_quote: "p, t, k",
    ex_analysis: "Obstruction articulatoire.",
  },
  {
    category: "Fonologi",
    lang: "fr",
    seq_no: 13,
    term: "Diphtongue",
    term_norm: "diphtongue",
    definition: "Suite de deux voyelles dans une syllabe.",
    def_citation: "Roach (2009)",
    ex_source: "Manuel",
    ex_date: "2020",
    ex_quote: "ai dans pays",
    ex_analysis: "Glissement vocalique.",
  },
  {
    category: "Fonologi",
    lang: "fr",
    seq_no: 14,
    term: "Nasalisation",
    term_norm: "nasalisation",
    definition: "Ajout du trait nasal a un son.",
    def_citation: "Crystal (2008)",
    ex_source: "Manuel",
    ex_date: "2020",
    ex_quote: "voyelle nasalisee",
    ex_analysis: "Air par le nez.",
  },
  {
    category: "Fonologi",
    lang: "fr",
    seq_no: 15,
    term: "Aspiration",
    term_norm: "aspiration",
    definition: "Souffle d'air apres l'occlusive.",
    def_citation: "Roach (2009)",
    ex_source: "Manuel",
    ex_date: "2020",
    ex_quote: "p souffle en anglais",
    ex_analysis: "Souffle audible.",
  },
  {
    category: "Fonologi",
    lang: "fr",
    seq_no: 16,
    term: "Lenition",
    term_norm: "lenition",
    definition: "Affaiblissement articulatoire.",
    def_citation: "Hyman (1975)",
    ex_source: "Manuel",
    ex_date: "2020",
    ex_quote: "t devient d",
    ex_analysis: "Perte d'energie.",
  },
  {
    category: "Fonologi",
    lang: "fr",
    seq_no: 17,
    term: "Fortition",
    term_norm: "fortition",
    definition: "Renforcement articulatoire.",
    def_citation: "Hyman (1975)",
    ex_source: "Manuel",
    ex_date: "2020",
    ex_quote: "s devient t",
    ex_analysis: "Gain d'energie.",
  },
  {
    category: "Fonologi",
    lang: "fr",
    seq_no: 18,
    term: "Métathèse",
    term_norm: "metathese",
    definition: "Permutation de segments dans un mot.",
    def_citation: "Campbell (2004)",
    ex_source: "Manuel",
    ex_date: "2020",
    ex_quote: "formage pour fromage",
    ex_analysis: "Inversion de segments.",
  },
  {
    category: "Fonologi",
    lang: "fr",
    seq_no: 19,
    term: "Elision",
    term_norm: "elision",
    definition: "Suppression d'un segment.",
    def_citation: "Crystal (2008)",
    ex_source: "Manuel",
    ex_date: "2020",
    ex_quote: "je ne sais pas -> j'sais pas",
    ex_analysis: "Segment efface.",
  },
  {
    category: "Fonologi",
    lang: "fr",
    seq_no: 20,
    term: "Harmonie vocalique",
    term_norm: "harmonie vocalique",
    definition: "Uniformisation des traits vocaliques.",
    def_citation: "Katamba (1989)",
    ex_source: "Manuel",
    ex_date: "2020",
    ex_quote: "voyelles arrondies dominantes",
    ex_analysis: "Accord vocalique.",
  },

  {
    category: "Sintaksis",
    lang: "id",
    seq_no: 1,
    term: "Frasa",
    term_norm: "frasa",
    definition: "Gabungan kata yang tidak membentuk klausa.",
    def_citation: "Referensi umum",
    ex_source: "Buku",
    ex_date: "2020",
    ex_quote: "rumah besar",
    ex_analysis: "Frasa nominal.",
  },
  {
    category: "Sintaksis",
    lang: "id",
    seq_no: 2,
    term: "Klausa",
    term_norm: "klausa",
    definition: "Satuan sintaksis dengan predikat.",
    def_citation: "Kajian umum",
    ex_source: "Buku",
    ex_date: "2020",
    ex_quote: "Dia pergi",
    ex_analysis: "Klausa sederhana.",
  },
  {
    category: "Sintaksis",
    lang: "id",
    seq_no: 3,
    term: "Kalimat",
    term_norm: "kalimat",
    definition: "Satuan bahasa lengkap.",
    def_citation: "Sumber umum",
    ex_source: "Buku",
    ex_date: "2020",
    ex_quote: "Dia pergi ke pasar.",
    ex_analysis: "Kalimat deklaratif.",
  },
  {
    category: "Sintaksis",
    lang: "id",
    seq_no: 4,
    term: "Subjek",
    term_norm: "subjek",
    definition: "Pelaku dalam kalimat.",
    def_citation: "Rujukan dasar",
    ex_source: "Buku",
    ex_date: "2020",
    ex_quote: "Dia makan nasi.",
    ex_analysis: "Dia sebagai subjek.",
  },
  {
    category: "Sintaksis",
    lang: "id",
    seq_no: 5,
    term: "Predikat",
    term_norm: "predikat",
    definition: "Bagian yang menjelaskan subjek.",
    def_citation: "Catatan umum",
    ex_source: "Buku",
    ex_date: "2020",
    ex_quote: "Dia makan nasi.",
    ex_analysis: "makan sebagai predikat.",
  },
  {
    category: "Sintaksis",
    lang: "id",
    seq_no: 6,
    term: "Objek",
    term_norm: "objek",
    definition: "Argumen yang dikenai tindakan predikat.",
    def_citation: "Carnie (2013)",
    ex_source: "Buku Sintaksis",
    ex_date: "2020",
    ex_quote: "Dia membaca buku.",
    ex_analysis: "buku sebagai objek.",
  },
  {
    category: "Sintaksis",
    lang: "id",
    seq_no: 7,
    term: "Komplemen",
    term_norm: "komplemen",
    definition: "Konstituen yang melengkapi predikat.",
    def_citation: "Radford (2004)",
    ex_source: "Buku",
    ex_date: "2020",
    ex_quote: "Dia tinggal di rumah.",
    ex_analysis: "di rumah sebagai komplemen.",
  },
  {
    category: "Sintaksis",
    lang: "id",
    seq_no: 8,
    term: "Keterangan",
    term_norm: "keterangan",
    definition: "Konstituen yang memberi informasi tambahan.",
    def_citation: "Verhaar (2001)",
    ex_source: "Buku",
    ex_date: "2020",
    ex_quote: "Dia datang kemarin.",
    ex_analysis: "kemarin sebagai keterangan.",
  },
  {
    category: "Sintaksis",
    lang: "id",
    seq_no: 9,
    term: "Inversi",
    term_norm: "inversi",
    definition: "Perubahan urutan normal konstituen.",
    def_citation: "Haegeman (1994)",
    ex_source: "Buku",
    ex_date: "2020",
    ex_quote: "Pergi dia ke pasar.",
    ex_analysis: "Predikat di depan.",
  },
  {
    category: "Sintaksis",
    lang: "id",
    seq_no: 10,
    term: "Koordinasi",
    term_norm: "koordinasi",
    definition: "Penggabungan dua konstituen setara.",
    def_citation: "Huddleston (2002)",
    ex_source: "Buku",
    ex_date: "2020",
    ex_quote: "Dia makan dan minum.",
    ex_analysis: "Konstituen setara.",
  },
  {
    category: "Sintaksis",
    lang: "id",
    seq_no: 11,
    term: "Subordinasi",
    term_norm: "subordinasi",
    definition: "Penggabungan klausa tidak setara.",
    def_citation: "Radford (2004)",
    ex_source: "Buku",
    ex_date: "2020",
    ex_quote: "Dia pergi karena hujan.",
    ex_analysis: "Klausa sebab.",
  },
  {
    category: "Sintaksis",
    lang: "id",
    seq_no: 12,
    term: "Relatifisasi",
    term_norm: "relatifisasi",
    definition: "Pembentukan klausa relatif.",
    def_citation: "Keenan & Comrie (1977)",
    ex_source: "Buku",
    ex_date: "2020",
    ex_quote: "Buku yang saya baca.",
    ex_analysis: "Klausa relatif.",
  },
  {
    category: "Sintaksis",
    lang: "id",
    seq_no: 13,
    term: "Topik",
    term_norm: "topik",
    definition: "Konstituen yang menjadi bahan pembicaraan.",
    def_citation: "Gundel (1988)",
    ex_source: "Buku",
    ex_date: "2020",
    ex_quote: "Tentang harga, dia diam.",
    ex_analysis: "Topik di awal.",
  },
  {
    category: "Sintaksis",
    lang: "id",
    seq_no: 14,
    term: "Fokus",
    term_norm: "fokus",
    definition: "Konstituen yang diberi penonjolan informasi.",
    def_citation: "Lambrecht (1994)",
    ex_source: "Buku",
    ex_date: "2020",
    ex_quote: "Yang dia beli adalah BUKU.",
    ex_analysis: "Fokus pada buku.",
  },
  {
    category: "Sintaksis",
    lang: "id",
    seq_no: 15,
    term: "Valensi",
    term_norm: "valensi",
    definition: "Jumlah argumen yang dituntut predikat.",
    def_citation: "Tesniere (1959)",
    ex_source: "Buku",
    ex_date: "2020",
    ex_quote: "memberi memerlukan tiga argumen.",
    ex_analysis: "Valensi tiga.",
  },
  {
    category: "Sintaksis",
    lang: "fr",
    seq_no: 6,
    term: "Phrase",
    term_norm: "phrase",
    definition: "Unité syntaxique complète.",
    def_citation: "Reference generale",
    ex_source: "Manuel",
    ex_date: "2020",
    ex_quote: "Il mange.",
    ex_analysis: "Phrase simple.",
  },
  {
    category: "Sintaksis",
    lang: "fr",
    seq_no: 7,
    term: "Proposition",
    term_norm: "proposition",
    definition: "Unité avec un verbe conjugué.",
    def_citation: "Source generale",
    ex_source: "Manuel",
    ex_date: "2020",
    ex_quote: "Il part",
    ex_analysis: "Proposition indépendante.",
  },
  {
    category: "Sintaksis",
    lang: "fr",
    seq_no: 8,
    term: "Sujet",
    term_norm: "sujet",
    definition: "Élément qui fait l’action.",
    def_citation: "Reference standard",
    ex_source: "Manuel",
    ex_date: "2020",
    ex_quote: "Il mange.",
    ex_analysis: "Il est sujet.",
  },
  {
    category: "Sintaksis",
    lang: "fr",
    seq_no: 9,
    term: "Prédicat",
    term_norm: "predicat",
    definition: "Partie qui décrit le sujet.",
    def_citation: "Note generale",
    ex_source: "Manuel",
    ex_date: "2020",
    ex_quote: "Il mange.",
    ex_analysis: "mange est prédicat.",
  },
  {
    category: "Sintaksis",
    lang: "fr",
    seq_no: 10,
    term: "Complément",
    term_norm: "complement",
    definition: "Élément ajouté au verbe.",
    def_citation: "Etude generale",
    ex_source: "Manuel",
    ex_date: "2020",
    ex_quote: "Il mange du pain.",
    ex_analysis: "du pain est complément.",
  },
  {
    category: "Sintaksis",
    lang: "fr",
    seq_no: 11,
    term: "Objet",
    term_norm: "objet",
    definition: "Argument qui subit l'action du predicat.",
    def_citation: "Carnie (2013)",
    ex_source: "Manuel de syntaxe",
    ex_date: "2020",
    ex_quote: "Il lit un livre.",
    ex_analysis: "livre comme objet.",
  },
  {
    category: "Sintaksis",
    lang: "fr",
    seq_no: 12,
    term: "Attribut",
    term_norm: "attribut",
    definition: "Constituant qui attribue une propriete au sujet.",
    def_citation: "Riegel (1994)",
    ex_source: "Manuel",
    ex_date: "2020",
    ex_quote: "Il est professeur.",
    ex_analysis: "professeur comme attribut.",
  },
  {
    category: "Sintaksis",
    lang: "fr",
    seq_no: 13,
    term: "Circonstanciel",
    term_norm: "circonstanciel",
    definition: "Constituant apportant une information additionnelle.",
    def_citation: "Verhaar (2001)",
    ex_source: "Manuel",
    ex_date: "2020",
    ex_quote: "Il vient demain.",
    ex_analysis: "demain comme circonstant.",
  },
  {
    category: "Sintaksis",
    lang: "fr",
    seq_no: 14,
    term: "Inversion",
    term_norm: "inversion",
    definition: "Changement de l'ordre canonique.",
    def_citation: "Haegeman (1994)",
    ex_source: "Manuel",
    ex_date: "2020",
    ex_quote: "Vient-il demain?",
    ex_analysis: "Verbe en tete.",
  },
  {
    category: "Sintaksis",
    lang: "fr",
    seq_no: 15,
    term: "Coordination",
    term_norm: "coordination",
    definition: "Jonction de deux constituants equivalents.",
    def_citation: "Huddleston (2002)",
    ex_source: "Manuel",
    ex_date: "2020",
    ex_quote: "Il mange et boit.",
    ex_analysis: "Constituants coordonnes.",
  },
  {
    category: "Sintaksis",
    lang: "fr",
    seq_no: 16,
    term: "Subordination",
    term_norm: "subordination",
    definition: "Jonction de clauses non equivalentes.",
    def_citation: "Radford (2004)",
    ex_source: "Manuel",
    ex_date: "2020",
    ex_quote: "Il part parce qu'il pleut.",
    ex_analysis: "Clause dependante.",
  },
  {
    category: "Sintaksis",
    lang: "fr",
    seq_no: 17,
    term: "Relativisation",
    term_norm: "relativisation",
    definition: "Formation d'une proposition relative.",
    def_citation: "Keenan & Comrie (1977)",
    ex_source: "Manuel",
    ex_date: "2020",
    ex_quote: "Le livre que j'ai lu.",
    ex_analysis: "Relative introduite.",
  },
  {
    category: "Sintaksis",
    lang: "fr",
    seq_no: 18,
    term: "Topique",
    term_norm: "topique",
    definition: "Constituant presente comme theme.",
    def_citation: "Gundel (1988)",
    ex_source: "Manuel",
    ex_date: "2020",
    ex_quote: "Quant au prix, il se tait.",
    ex_analysis: "Topique initial.",
  },
  {
    category: "Sintaksis",
    lang: "fr",
    seq_no: 19,
    term: "Focalisation",
    term_norm: "focalisation",
    definition: "Mise en relief d'un constituant.",
    def_citation: "Lambrecht (1994)",
    ex_source: "Manuel",
    ex_date: "2020",
    ex_quote: "C'est LE LIVRE qu'il a achete.",
    ex_analysis: "Focus sur livre.",
  },
  {
    category: "Sintaksis",
    lang: "fr",
    seq_no: 20,
    term: "Valence",
    term_norm: "valence",
    definition: "Nombre d'arguments requis par le predicat.",
    def_citation: "Tesniere (1959)",
    ex_source: "Manuel",
    ex_date: "2020",
    ex_quote: "donner exige trois arguments.",
    ex_analysis: "Valence trois.",
  },

  {
    category: "Semantik",
    lang: "id",
    seq_no: 1,
    term: "Denotasi",
    term_norm: "denotasi",
    definition: "Makna literal.",
    def_citation: "Rujukan dasar",
    ex_source: "Buku",
    ex_date: "2020",
    ex_quote: "mawar = bunga",
    ex_analysis: "Makna langsung.",
  },
  {
    category: "Semantik",
    lang: "id",
    seq_no: 2,
    term: "Konotasi",
    term_norm: "konotasi",
    definition: "Makna tambahan.",
    def_citation: "Sumber umum",
    ex_source: "Buku",
    ex_date: "2020",
    ex_quote: "mawar = cinta",
    ex_analysis: "Makna emosional.",
  },
  {
    category: "Semantik",
    lang: "id",
    seq_no: 3,
    term: "Sinonim",
    term_norm: "sinonim",
    definition: "Makna sama.",
    def_citation: "Referensi umum",
    ex_source: "Buku",
    ex_date: "2020",
    ex_quote: "besar = agung",
    ex_analysis: "Kesamaan makna.",
  },
  {
    category: "Semantik",
    lang: "id",
    seq_no: 4,
    term: "Antonim",
    term_norm: "antonim",
    definition: "Makna berlawanan.",
    def_citation: "Catatan umum",
    ex_source: "Buku",
    ex_date: "2020",
    ex_quote: "besar vs kecil",
    ex_analysis: "Kontras.",
  },
  {
    category: "Semantik",
    lang: "id",
    seq_no: 5,
    term: "Polisemi",
    term_norm: "polisemi",
    definition: "Satu kata banyak makna.",
    def_citation: "Kajian umum",
    ex_source: "Buku",
    ex_date: "2020",
    ex_quote: "kepala",
    ex_analysis: "Makna beragam.",
  },
  {
    category: "Semantik",
    lang: "id",
    seq_no: 6,
    term: "Hiponim",
    term_norm: "hiponim",
    definition: "Relasi makna khusus terhadap makna umum.",
    def_citation: "Lyons (1977)",
    ex_source: "Buku Semantik",
    ex_date: "2020",
    ex_quote: "mawar adalah hiponim bunga.",
    ex_analysis: "Relasi khusus-umum.",
  },
  {
    category: "Semantik",
    lang: "id",
    seq_no: 7,
    term: "Hiperonim",
    term_norm: "hiperonim",
    definition: "Makna umum yang menaungi makna khusus.",
    def_citation: "Lyons (1977)",
    ex_source: "Buku",
    ex_date: "2020",
    ex_quote: "bunga adalah hiperonim mawar.",
    ex_analysis: "Makna superordinat.",
  },
  {
    category: "Semantik",
    lang: "id",
    seq_no: 8,
    term: "Homonim",
    term_norm: "homonim",
    definition: "Dua kata sama bentuk dengan makna berbeda.",
    def_citation: "Cruse (2000)",
    ex_source: "Buku",
    ex_date: "2020",
    ex_quote: "bisa (racun) vs bisa (mampu)",
    ex_analysis: "Bentuk sama, makna beda.",
  },
  {
    category: "Semantik",
    lang: "id",
    seq_no: 9,
    term: "Homofon",
    term_norm: "homofon",
    definition: "Pelafalan sama dengan ejaan atau makna berbeda.",
    def_citation: "Cruse (2000)",
    ex_source: "Buku",
    ex_date: "2020",
    ex_quote: "masa vs massa",
    ex_analysis: "Bunyi sama.",
  },
  {
    category: "Semantik",
    lang: "id",
    seq_no: 10,
    term: "Homograf",
    term_norm: "homograf",
    definition: "Ejaan sama dengan pelafalan atau makna berbeda.",
    def_citation: "Cruse (2000)",
    ex_source: "Buku",
    ex_date: "2020",
    ex_quote: "apel (buah) vs apel (upacara)",
    ex_analysis: "Ejaan sama.",
  },
  {
    category: "Semantik",
    lang: "id",
    seq_no: 11,
    term: "Metonimi",
    term_norm: "metonimi",
    definition: "Pergantian makna berdasarkan kedekatan.",
    def_citation: "Lakoff & Johnson (1980)",
    ex_source: "Buku",
    ex_date: "2020",
    ex_quote: "Ia membaca Pramoedya.",
    ex_analysis: "Penulis menggantikan karya.",
  },
  {
    category: "Semantik",
    lang: "id",
    seq_no: 12,
    term: "Metafora",
    term_norm: "metafora",
    definition: "Pemindahan makna berdasarkan kemiripan.",
    def_citation: "Lakoff & Johnson (1980)",
    ex_source: "Buku",
    ex_date: "2020",
    ex_quote: "lautan manusia",
    ex_analysis: "Kesamaan sifat.",
  },
  {
    category: "Semantik",
    lang: "id",
    seq_no: 13,
    term: "Ambiguitas",
    term_norm: "ambiguitas",
    definition: "Ketaksaan makna dalam ujaran.",
    def_citation: "Katz (1972)",
    ex_source: "Buku",
    ex_date: "2020",
    ex_quote: "Dia melihat orang dengan teropong.",
    ex_analysis: "Dua interpretasi.",
  },
  {
    category: "Semantik",
    lang: "id",
    seq_no: 14,
    term: "Meronim",
    term_norm: "meronim",
    definition: "Relasi bagian terhadap keseluruhan.",
    def_citation: "Cruse (2000)",
    ex_source: "Buku",
    ex_date: "2020",
    ex_quote: "roda adalah meronim mobil.",
    ex_analysis: "Relasi bagian-keseluruhan.",
  },
  {
    category: "Semantik",
    lang: "id",
    seq_no: 15,
    term: "Entailmen",
    term_norm: "entailmen",
    definition: "Makna kalimat yang mengharuskan kalimat lain benar.",
    def_citation: "Levinson (1983)",
    ex_source: "Buku",
    ex_date: "2020",
    ex_quote: "Dia membunuh sapi.",
    ex_analysis: "Mengimplikasikan sapi mati.",
  },
  {
    category: "Semantik",
    lang: "fr",
    seq_no: 6,
    term: "Dénotation",
    term_norm: "denotation",
    definition: "Sens littéral.",
    def_citation: "Reference generale",
    ex_source: "Manuel",
    ex_date: "2020",
    ex_quote: "rose = fleur",
    ex_analysis: "Sens direct.",
  },
  {
    category: "Semantik",
    lang: "fr",
    seq_no: 7,
    term: "Connotation",
    term_norm: "connotation",
    definition: "Sens implicite.",
    def_citation: "Source generale",
    ex_source: "Manuel",
    ex_date: "2020",
    ex_quote: "rose = amour",
    ex_analysis: "Valeur symbolique.",
  },
  {
    category: "Semantik",
    lang: "fr",
    seq_no: 8,
    term: "Synonyme",
    term_norm: "synonyme",
    definition: "Mots de sens proche.",
    def_citation: "Reference standard",
    ex_source: "Manuel",
    ex_date: "2020",
    ex_quote: "grand = immense",
    ex_analysis: "Proximité sémantique.",
  },
  {
    category: "Semantik",
    lang: "fr",
    seq_no: 9,
    term: "Antonyme",
    term_norm: "antonyme",
    definition: "Sens opposé.",
    def_citation: "Note generale",
    ex_source: "Manuel",
    ex_date: "2020",
    ex_quote: "grand vs petit",
    ex_analysis: "Opposition.",
  },
  {
    category: "Semantik",
    lang: "fr",
    seq_no: 10,
    term: "Polysémie",
    term_norm: "polysemie",
    definition: "Mot à plusieurs sens.",
    def_citation: "Etude generale",
    ex_source: "Manuel",
    ex_date: "2020",
    ex_quote: "tête",
    ex_analysis: "Multiplicité de sens.",
  },
  {
    category: "Semantik",
    lang: "fr",
    seq_no: 11,
    term: "Hyponyme",
    term_norm: "hyponyme",
    definition: "Relation de sens specifique par rapport au general.",
    def_citation: "Lyons (1977)",
    ex_source: "Manuel de semantique",
    ex_date: "2020",
    ex_quote: "rose est un hyponyme de fleur.",
    ex_analysis: "Relation specifique-general.",
  },
  {
    category: "Semantik",
    lang: "fr",
    seq_no: 12,
    term: "Hyperonyme",
    term_norm: "hyperonyme",
    definition: "Terme general englobant des termes specifiques.",
    def_citation: "Lyons (1977)",
    ex_source: "Manuel",
    ex_date: "2020",
    ex_quote: "fleur est un hyperonyme de rose.",
    ex_analysis: "Sens superordonne.",
  },
  {
    category: "Semantik",
    lang: "fr",
    seq_no: 13,
    term: "Homonyme",
    term_norm: "homonyme",
    definition: "Deux mots de meme forme avec sens different.",
    def_citation: "Cruse (2000)",
    ex_source: "Manuel",
    ex_date: "2020",
    ex_quote: "verre vs vers",
    ex_analysis: "Forme identique.",
  },
  {
    category: "Semantik",
    lang: "fr",
    seq_no: 14,
    term: "Homophone",
    term_norm: "homophone",
    definition: "Prononciation identique, ecriture ou sens different.",
    def_citation: "Cruse (2000)",
    ex_source: "Manuel",
    ex_date: "2020",
    ex_quote: "mer vs mere",
    ex_analysis: "Son identique.",
  },
  {
    category: "Semantik",
    lang: "fr",
    seq_no: 15,
    term: "Homographe",
    term_norm: "homographe",
    definition: "Ecriture identique, prononciation ou sens different.",
    def_citation: "Cruse (2000)",
    ex_source: "Manuel",
    ex_date: "2020",
    ex_quote: "couvent (nom) vs couvent (verbe)",
    ex_analysis: "Graphie identique.",
  },
  {
    category: "Semantik",
    lang: "fr",
    seq_no: 16,
    term: "Metonymie",
    term_norm: "metonymie",
    definition: "Substitution basee sur la contiguite.",
    def_citation: "Lakoff & Johnson (1980)",
    ex_source: "Manuel",
    ex_date: "2020",
    ex_quote: "Il lit Balzac.",
    ex_analysis: "Auteur pour oeuvre.",
  },
  {
    category: "Semantik",
    lang: "fr",
    seq_no: 17,
    term: "Métaphore",
    term_norm: "metaphore",
    definition: "Transfert de sens par similitude.",
    def_citation: "Lakoff & Johnson (1980)",
    ex_source: "Manuel",
    ex_date: "2020",
    ex_quote: "une mer de gens",
    ex_analysis: "Similarite d'image.",
  },
  {
    category: "Semantik",
    lang: "fr",
    seq_no: 18,
    term: "Ambiguïté",
    term_norm: "ambiguite",
    definition: "Pluralite d'interpretations possibles.",
    def_citation: "Katz (1972)",
    ex_source: "Manuel",
    ex_date: "2020",
    ex_quote: "Il voit l'homme avec des jumelles.",
    ex_analysis: "Deux lectures.",
  },
  {
    category: "Semantik",
    lang: "fr",
    seq_no: 19,
    term: "Meronymie",
    term_norm: "meronymie",
    definition: "Relation partie-tout.",
    def_citation: "Cruse (2000)",
    ex_source: "Manuel",
    ex_date: "2020",
    ex_quote: "roue est un meronyme de voiture.",
    ex_analysis: "Partie et tout.",
  },
  {
    category: "Semantik",
    lang: "fr",
    seq_no: 20,
    term: "Implication",
    term_norm: "implication",
    definition: "Relation ou la verite d'un enonce entraine celle d'un autre.",
    def_citation: "Levinson (1983)",
    ex_source: "Manuel",
    ex_date: "2020",
    ex_quote: "Il a tue un animal.",
    ex_analysis: "L'animal est mort.",
  },

  {
    category: "Pragmatik",
    lang: "id",
    seq_no: 1,
    term: "Implikatur",
    term_norm: "implikatur",
    definition: "Makna tersirat.",
    def_citation: "Grice",
    ex_source: "Dialog",
    ex_date: "2020",
    ex_quote: "Sudah jam 10.",
    ex_analysis: "Menyuruh pulang.",
  },
  {
    category: "Pragmatik",
    lang: "id",
    seq_no: 2,
    term: "Deiksis",
    term_norm: "deiksis",
    definition: "Rujukan kontekstual.",
    def_citation: "Sumber umum",
    ex_source: "Dialog",
    ex_date: "2020",
    ex_quote: "di sini",
    ex_analysis: "Tergantung konteks.",
  },
  {
    category: "Pragmatik",
    lang: "id",
    seq_no: 3,
    term: "Tindak tutur",
    term_norm: "tindak tutur",
    definition: "Aksi melalui bahasa.",
    def_citation: "Austin",
    ex_source: "Dialog",
    ex_date: "2020",
    ex_quote: "Saya janji.",
    ex_analysis: "Komisif.",
  },
  {
    category: "Pragmatik",
    lang: "id",
    seq_no: 4,
    term: "Presuposisi",
    term_norm: "presuposisi",
    definition: "Asumsi awal.",
    def_citation: "Referensi umum",
    ex_source: "Dialog",
    ex_date: "2020",
    ex_quote: "Dia berhenti merokok.",
    ex_analysis: "Pernah merokok.",
  },
  {
    category: "Pragmatik",
    lang: "id",
    seq_no: 5,
    term: "Kesantunan",
    term_norm: "kesantunan",
    definition: "Strategi menjaga hubungan sosial.",
    def_citation: "Brown & Levinson",
    ex_source: "Dialog",
    ex_date: "2020",
    ex_quote: "Maaf mengganggu.",
    ex_analysis: "Strategi sopan.",
  },
  {
    category: "Pragmatik",
    lang: "id",
    seq_no: 6,
    term: "Lokusi",
    term_norm: "lokusi",
    definition: "Tindak ujaran sebagai produksi bentuk linguistik.",
    def_citation: "Austin (1962)",
    ex_source: "Dialog",
    ex_date: "2020",
    ex_quote: "Saya lapar.",
    ex_analysis: "Tindakan mengatakan.",
  },
  {
    category: "Pragmatik",
    lang: "id",
    seq_no: 7,
    term: "Ilokusi",
    term_norm: "ilokusi",
    definition: "Maksud tindakan di balik ujaran.",
    def_citation: "Searle (1969)",
    ex_source: "Dialog",
    ex_date: "2020",
    ex_quote: "Tolong tutup pintu.",
    ex_analysis: "Permintaan.",
  },
  {
    category: "Pragmatik",
    lang: "id",
    seq_no: 8,
    term: "Perlokusi",
    term_norm: "perlokusi",
    definition: "Dampak ujaran pada pendengar.",
    def_citation: "Austin (1962)",
    ex_source: "Dialog",
    ex_date: "2020",
    ex_quote: "Saya janji.",
    ex_analysis: "Membuat yakin.",
  },
  {
    category: "Pragmatik",
    lang: "id",
    seq_no: 9,
    term: "Maksim kuantitas",
    term_norm: "maksim kuantitas",
    definition: "Berikan informasi secukupnya.",
    def_citation: "Grice (1975)",
    ex_source: "Dialog",
    ex_date: "2020",
    ex_quote: "Dia datang jam delapan.",
    ex_analysis: "Informasi cukup.",
  },
  {
    category: "Pragmatik",
    lang: "id",
    seq_no: 10,
    term: "Maksim kualitas",
    term_norm: "maksim kualitas",
    definition: "Ucapkan yang benar.",
    def_citation: "Grice (1975)",
    ex_source: "Dialog",
    ex_date: "2020",
    ex_quote: "Saya melihatnya sendiri.",
    ex_analysis: "Komitmen kebenaran.",
  },
  {
    category: "Pragmatik",
    lang: "id",
    seq_no: 11,
    term: "Maksim relevansi",
    term_norm: "maksim relevansi",
    definition: "Ujaran harus relevan.",
    def_citation: "Grice (1975)",
    ex_source: "Dialog",
    ex_date: "2020",
    ex_quote: "Pertanyaannya dijawab langsung.",
    ex_analysis: "Relevan konteks.",
  },
  {
    category: "Pragmatik",
    lang: "id",
    seq_no: 12,
    term: "Maksim cara",
    term_norm: "maksim cara",
    definition: "Ujaran harus jelas dan teratur.",
    def_citation: "Grice (1975)",
    ex_source: "Dialog",
    ex_date: "2020",
    ex_quote: "Jelaskan langkah demi langkah.",
    ex_analysis: "Kejelasan.",
  },
  {
    category: "Pragmatik",
    lang: "id",
    seq_no: 13,
    term: "Giliran tutur",
    term_norm: "giliran tutur",
    definition: "Pengaturan pergantian pembicara.",
    def_citation: "Sacks et al. (1974)",
    ex_source: "Dialog",
    ex_date: "2020",
    ex_quote: "Dia berhenti, lalu yang lain mulai.",
    ex_analysis: "Pergantian giliran.",
  },
  {
    category: "Pragmatik",
    lang: "id",
    seq_no: 14,
    term: "Penjagaan muka",
    term_norm: "penjagaan muka",
    definition: "Strategi menjaga citra sosial.",
    def_citation: "Goffman (1967)",
    ex_source: "Dialog",
    ex_date: "2020",
    ex_quote: "Maaf, boleh saya minta bantuan?",
    ex_analysis: "Menjaga muka lawan tutur.",
  },
  {
    category: "Pragmatik",
    lang: "id",
    seq_no: 15,
    term: "Deiksis sosial",
    term_norm: "deiksis sosial",
    definition: "Rujukan yang menandai relasi sosial.",
    def_citation: "Levinson (1983)",
    ex_source: "Dialog",
    ex_date: "2020",
    ex_quote: "Beliau akan hadir.",
    ex_analysis: "Penanda hormat.",
  },
  {
    category: "Pragmatik",
    lang: "fr",
    seq_no: 6,
    term: "Implicature",
    term_norm: "implicature",
    definition: "Sens implicite.",
    def_citation: "Grice",
    ex_source: "Dialogue",
    ex_date: "2020",
    ex_quote: "Il est tard.",
    ex_analysis: "Suggestion indirecte.",
  },
  {
    category: "Pragmatik",
    lang: "fr",
    seq_no: 7,
    term: "Déixis",
    term_norm: "deixis",
    definition: "Référence contextuelle.",
    def_citation: "Reference generale",
    ex_source: "Dialogue",
    ex_date: "2020",
    ex_quote: "ici",
    ex_analysis: "Dépend du contexte.",
  },
  {
    category: "Pragmatik",
    lang: "fr",
    seq_no: 8,
    term: "Acte de parole",
    term_norm: "acte de parole",
    definition: "Action réalisée par langage.",
    def_citation: "Austin",
    ex_source: "Dialogue",
    ex_date: "2020",
    ex_quote: "Je promets.",
    ex_analysis: "Acte commissif.",
  },
  {
    category: "Pragmatik",
    lang: "fr",
    seq_no: 9,
    term: "Présupposition",
    term_norm: "presupposition",
    definition: "Hypothèse implicite.",
    def_citation: "Source generale",
    ex_source: "Dialogue",
    ex_date: "2020",
    ex_quote: "Il a arrêté de fumer.",
    ex_analysis: "Fumait avant.",
  },
  {
    category: "Pragmatik",
    lang: "fr",
    seq_no: 10,
    term: "Politesse",
    term_norm: "politesse",
    definition: "Stratégies sociales.",
    def_citation: "Brown & Levinson",
    ex_source: "Dialogue",
    ex_date: "2020",
    ex_quote: "Excusez-moi.",
    ex_analysis: "Stratégie de politesse.",
  },
  {
    category: "Pragmatik",
    lang: "fr",
    seq_no: 11,
    term: "Locution",
    term_norm: "locution",
    definition: "Acte d'énoncer une forme linguistique.",
    def_citation: "Austin (1962)",
    ex_source: "Dialogue",
    ex_date: "2020",
    ex_quote: "J'ai faim.",
    ex_analysis: "Acte de dire.",
  },
  {
    category: "Pragmatik",
    lang: "fr",
    seq_no: 12,
    term: "Illocution",
    term_norm: "illocution",
    definition: "Intention de l'acte de parole.",
    def_citation: "Searle (1969)",
    ex_source: "Dialogue",
    ex_date: "2020",
    ex_quote: "Fermez la porte, s'il vous plait.",
    ex_analysis: "Demande.",
  },
  {
    category: "Pragmatik",
    lang: "fr",
    seq_no: 13,
    term: "Perlocution",
    term_norm: "perlocution",
    definition: "Effet de l'énoncé sur l'auditeur.",
    def_citation: "Austin (1962)",
    ex_source: "Dialogue",
    ex_date: "2020",
    ex_quote: "Je te promets.",
    ex_analysis: "Rassurer l'autre.",
  },
  {
    category: "Pragmatik",
    lang: "fr",
    seq_no: 14,
    term: "Maxime de quantite",
    term_norm: "maxime de quantite",
    definition: "Donner la quantite d'information adequate.",
    def_citation: "Grice (1975)",
    ex_source: "Dialogue",
    ex_date: "2020",
    ex_quote: "Il arrive a huit heures.",
    ex_analysis: "Information suffisante.",
  },
  {
    category: "Pragmatik",
    lang: "fr",
    seq_no: 15,
    term: "Maxime de qualite",
    term_norm: "maxime de qualite",
    definition: "Ne dire que ce qui est vrai.",
    def_citation: "Grice (1975)",
    ex_source: "Dialogue",
    ex_date: "2020",
    ex_quote: "Je l'ai vu moi-meme.",
    ex_analysis: "Engagement a la verite.",
  },
  {
    category: "Pragmatik",
    lang: "fr",
    seq_no: 16,
    term: "Maxime de relation",
    term_norm: "maxime de relation",
    definition: "L'énoncé doit etre pertinent.",
    def_citation: "Grice (1975)",
    ex_source: "Dialogue",
    ex_date: "2020",
    ex_quote: "Il repond directement a la question.",
    ex_analysis: "Pertinence.",
  },
  {
    category: "Pragmatik",
    lang: "fr",
    seq_no: 17,
    term: "Maxime de maniere",
    term_norm: "maxime de maniere",
    definition: "L'énoncé doit etre clair et ordonne.",
    def_citation: "Grice (1975)",
    ex_source: "Dialogue",
    ex_date: "2020",
    ex_quote: "Expliquez etape par etape.",
    ex_analysis: "Clarite.",
  },
  {
    category: "Pragmatik",
    lang: "fr",
    seq_no: 18,
    term: "Tour de parole",
    term_norm: "tour de parole",
    definition: "Gestion de l'alternance des locuteurs.",
    def_citation: "Sacks et al. (1974)",
    ex_source: "Dialogue",
    ex_date: "2020",
    ex_quote: "Il s'arrete, puis l'autre commence.",
    ex_analysis: "Alternance.",
  },
  {
    category: "Pragmatik",
    lang: "fr",
    seq_no: 19,
    term: "Travail de face",
    term_norm: "travail de face",
    definition: "Strategies pour proteger l'image sociale.",
    def_citation: "Goffman (1967)",
    ex_source: "Dialogue",
    ex_date: "2020",
    ex_quote: "Excusez-moi, puis-je demander?",
    ex_analysis: "Protection de la face.",
  },
  {
    category: "Pragmatik",
    lang: "fr",
    seq_no: 20,
    term: "Déixis sociale",
    term_norm: "deixis sociale",
    definition: "Reference qui marque la relation sociale.",
    def_citation: "Levinson (1983)",
    ex_source: "Dialogue",
    ex_date: "2020",
    ex_quote: "Il viendra, Monsieur.",
    ex_analysis: "Marque de respect.",
  },

  {
    category: "Morfologi",
    lang: "id",
    seq_no: 1,
    term: "Morfem",
    term_norm: "morfem",
    definition: "Unit terkecil bermakna.",
    def_citation: "Sumber umum",
    ex_source: "Buku",
    ex_date: "2020",
    ex_quote: "ber-",
    ex_analysis: "Prefiks.",
  },
  {
    category: "Morfologi",
    lang: "id",
    seq_no: 2,
    term: "Afiksasi",
    term_norm: "afiksasi",
    definition: "Proses penambahan afiks.",
    def_citation: "Referensi umum",
    ex_source: "Buku",
    ex_date: "2020",
    ex_quote: "me-kan",
    ex_analysis: "Pembentukan kata.",
  },
  {
    category: "Morfologi",
    lang: "id",
    seq_no: 3,
    term: "Reduplikasi",
    term_norm: "reduplikasi",
    definition: "Pengulangan kata.",
    def_citation: "Rujukan dasar",
    ex_source: "Buku",
    ex_date: "2020",
    ex_quote: "buku-buku",
    ex_analysis: "Pluralitas.",
  },
  {
    category: "Morfologi",
    lang: "id",
    seq_no: 4,
    term: "Komposisi",
    term_norm: "komposisi",
    definition: "Penggabungan kata.",
    def_citation: "Kajian umum",
    ex_source: "Buku",
    ex_date: "2020",
    ex_quote: "rumah sakit",
    ex_analysis: "Makna baru.",
  },
  {
    category: "Morfologi",
    lang: "id",
    seq_no: 5,
    term: "Derivasi",
    term_norm: "derivasi",
    definition: "Pembentukan kata baru.",
    def_citation: "Catatan umum",
    ex_source: "Buku",
    ex_date: "2020",
    ex_quote: "ajar → pelajar",
    ex_analysis: "Perubahan kelas kata.",
  },
  {
    category: "Morfologi",
    lang: "id",
    seq_no: 6,
    term: "Infleksi",
    term_norm: "infleksi",
    definition: "Proses morfologis yang tidak mengubah kelas kata.",
    def_citation: "Katamba (1993)",
    ex_source: "Buku",
    ex_date: "2020",
    ex_quote: "walk menjadi walked",
    ex_analysis: "Perubahan gramatikal.",
  },
  {
    category: "Morfologi",
    lang: "id",
    seq_no: 7,
    term: "Prefiksasi",
    term_norm: "prefiksasi",
    definition: "Penambahan prefiks pada dasar.",
    def_citation: "Katamba (1993)",
    ex_source: "Buku",
    ex_date: "2020",
    ex_quote: "ber- + jalan",
    ex_analysis: "Pembentukan kata.",
  },
  {
    category: "Morfologi",
    lang: "id",
    seq_no: 8,
    term: "Sufiksasi",
    term_norm: "sufiksasi",
    definition: "Penambahan sufiks pada dasar.",
    def_citation: "Katamba (1993)",
    ex_source: "Buku",
    ex_date: "2020",
    ex_quote: "-an pada tulisan",
    ex_analysis: "Perluasan makna.",
  },
  {
    category: "Morfologi",
    lang: "id",
    seq_no: 9,
    term: "Infixasi",
    term_norm: "infixasi",
    definition: "Penyisipan afiks di tengah dasar.",
    def_citation: "Ramlan (2001)",
    ex_source: "Buku",
    ex_date: "2020",
    ex_quote: "gigi menjadi g-in-igi",
    ex_analysis: "Sisipan.",
  },
  {
    category: "Morfologi",
    lang: "id",
    seq_no: 10,
    term: "Konfiksasi",
    term_norm: "konfiksasi",
    definition: "Penambahan konfiks secara bersamaan.",
    def_citation: "Ramlan (2001)",
    ex_source: "Buku",
    ex_date: "2020",
    ex_quote: "ke- -an",
    ex_analysis: "Pembentukan nomina.",
  },
  {
    category: "Morfologi",
    lang: "id",
    seq_no: 11,
    term: "Klitika",
    term_norm: "klitika",
    definition: "Bentuk terikat yang berperilaku seperti kata.",
    def_citation: "Zwicky (1985)",
    ex_source: "Buku",
    ex_date: "2020",
    ex_quote: "ku- pada kubaca",
    ex_analysis: "Klitik pronominal.",
  },
  {
    category: "Morfologi",
    lang: "id",
    seq_no: 12,
    term: "Konversi",
    term_norm: "konversi",
    definition: "Perubahan kelas kata tanpa afiks.",
    def_citation: "Bauer (2003)",
    ex_source: "Buku",
    ex_date: "2020",
    ex_quote: "to email",
    ex_analysis: "Verba dari nomina.",
  },
  {
    category: "Morfologi",
    lang: "id",
    seq_no: 13,
    term: "Akronim",
    term_norm: "akronim",
    definition: "Pembentukan kata dari huruf awal.",
    def_citation: "Kridalaksana (2007)",
    ex_source: "Buku",
    ex_date: "2020",
    ex_quote: "LAN",
    ex_analysis: "Akronim.",
  },
  {
    category: "Morfologi",
    lang: "id",
    seq_no: 14,
    term: "Singkatan",
    term_norm: "singkatan",
    definition: "Pemendekan dengan huruf awal.",
    def_citation: "Kridalaksana (2007)",
    ex_source: "Buku",
    ex_date: "2020",
    ex_quote: "PT",
    ex_analysis: "Singkatan.",
  },
  {
    category: "Morfologi",
    lang: "id",
    seq_no: 15,
    term: "Pemendekan",
    term_norm: "pemendekan",
    definition: "Pemotongan bagian kata.",
    def_citation: "Bauer (2003)",
    ex_source: "Buku",
    ex_date: "2020",
    ex_quote: "foto dari fotografi",
    ex_analysis: "Clipping.",
  },
  {
    category: "Morfologi",
    lang: "fr",
    seq_no: 6,
    term: "Morphème",
    term_norm: "morpheme",
    definition: "Plus petite unité significative.",
    def_citation: "Reference generale",
    ex_source: "Manuel",
    ex_date: "2020",
    ex_quote: "re-",
    ex_analysis: "Préfixe.",
  },
  {
    category: "Morfologi",
    lang: "fr",
    seq_no: 7,
    term: "Affixation",
    term_norm: "affixation",
    definition: "Ajout d’affixes.",
    def_citation: "Source generale",
    ex_source: "Manuel",
    ex_date: "2020",
    ex_quote: "revenir",
    ex_analysis: "Préfixation.",
  },
  {
    category: "Morfologi",
    lang: "fr",
    seq_no: 8,
    term: "Reduplication",
    term_norm: "reduplication",
    definition: "Répétition morphologique.",
    def_citation: "Note generale",
    ex_source: "Manuel",
    ex_date: "2020",
    ex_quote: "très très",
    ex_analysis: "Intensification.",
  },
  {
    category: "Morfologi",
    lang: "fr",
    seq_no: 9,
    term: "Composition",
    term_norm: "composition",
    definition: "Combinaison de mots.",
    def_citation: "Reference standard",
    ex_source: "Manuel",
    ex_date: "2020",
    ex_quote: "portefeuille",
    ex_analysis: "Mot composé.",
  },
  {
    category: "Morfologi",
    lang: "fr",
    seq_no: 10,
    term: "Dérivation",
    term_norm: "derivation",
    definition: "Formation de nouveaux mots.",
    def_citation: "Etude generale",
    ex_source: "Manuel",
    ex_date: "2020",
    ex_quote: "chanter → chanteur",
    ex_analysis: "Changement de catégorie.",
  },
  {
    category: "Morfologi",
    lang: "fr",
    seq_no: 11,
    term: "Inflection",
    term_norm: "inflection",
    definition: "Processus morphologique sans changement de categorie.",
    def_citation: "Katamba (1993)",
    ex_source: "Manuel",
    ex_date: "2020",
    ex_quote: "walk devient walked",
    ex_analysis: "Changement grammatical.",
  },
  {
    category: "Morfologi",
    lang: "fr",
    seq_no: 12,
    term: "Préfixation",
    term_norm: "prefixation",
    definition: "Ajout d'un prefixe a une base.",
    def_citation: "Katamba (1993)",
    ex_source: "Manuel",
    ex_date: "2020",
    ex_quote: "re- + lire",
    ex_analysis: "Formation de mot.",
  },
  {
    category: "Morfologi",
    lang: "fr",
    seq_no: 13,
    term: "Suffixation",
    term_norm: "suffixation",
    definition: "Ajout d'un suffixe a une base.",
    def_citation: "Katamba (1993)",
    ex_source: "Manuel",
    ex_date: "2020",
    ex_quote: "-eur dans chanteur",
    ex_analysis: "Derivation.",
  },
  {
    category: "Morfologi",
    lang: "fr",
    seq_no: 14,
    term: "Infixation",
    term_norm: "infixation",
    definition: "Insertion d'un affixe a l'interieur de la base.",
    def_citation: "Ramlan (2001)",
    ex_source: "Manuel",
    ex_date: "2020",
    ex_quote: "gigi devient g-in-igi",
    ex_analysis: "Insertion interne.",
  },
  {
    category: "Morfologi",
    lang: "fr",
    seq_no: 15,
    term: "Circonfixation",
    term_norm: "circonfixation",
    definition: "Ajout simultane d'un circonfixe.",
    def_citation: "Ramlan (2001)",
    ex_source: "Manuel",
    ex_date: "2020",
    ex_quote: "en- -er",
    ex_analysis: "Formation nominale.",
  },
  {
    category: "Morfologi",
    lang: "fr",
    seq_no: 16,
    term: "Clitique",
    term_norm: "clitique",
    definition: "Forme liee qui se comporte comme un mot.",
    def_citation: "Zwicky (1985)",
    ex_source: "Manuel",
    ex_date: "2020",
    ex_quote: "je l'ai vu",
    ex_analysis: "Clitique pronominal.",
  },
  {
    category: "Morfologi",
    lang: "fr",
    seq_no: 17,
    term: "Conversion",
    term_norm: "conversion",
    definition: "Changement de categorie sans affixe.",
    def_citation: "Bauer (2003)",
    ex_source: "Manuel",
    ex_date: "2020",
    ex_quote: "email devient verbe",
    ex_analysis: "Nom vers verbe.",
  },
  {
    category: "Morfologi",
    lang: "fr",
    seq_no: 18,
    term: "Acronyme",
    term_norm: "acronyme",
    definition: "Mot forme a partir d'initiales.",
    def_citation: "Kridalaksana (2007)",
    ex_source: "Manuel",
    ex_date: "2020",
    ex_quote: "ONU",
    ex_analysis: "Acronyme.",
  },
  {
    category: "Morfologi",
    lang: "fr",
    seq_no: 19,
    term: "Sigle",
    term_norm: "sigle",
    definition: "Abreviation par lettres initiales.",
    def_citation: "Kridalaksana (2007)",
    ex_source: "Manuel",
    ex_date: "2020",
    ex_quote: "SNCF",
    ex_analysis: "Sigle.",
  },
  {
    category: "Morfologi",
    lang: "fr",
    seq_no: 20,
    term: "Troncation",
    term_norm: "troncation",
    definition: "Reduction d'un mot par suppression.",
    def_citation: "Bauer (2003)",
    ex_source: "Manuel",
    ex_date: "2020",
    ex_quote: "photo pour photographie",
    ex_analysis: "Clipping.",
  },
];

const FALLBACK_CATEGORY_KEY = "Fonologi";
const FALLBACK_CATEGORY_ID =
  translations.ID.home.categories.find(
    (category) => category.title === FALLBACK_CATEGORY_KEY,
  )?.id ?? "1";

const LANGUAGE_MAP: Record<Language, "id" | "fr"> = {
  ID: "id",
  FR: "fr",
};

function mapLanguage(language: Language) {
  return LANGUAGE_MAP[language];
}

function slugifyCategoryTitle(title: string) {
  return title
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "");
}

function getCategoryKeyById(categoryId: string) {
  return (
    translations.ID.home.categories.find(
      (category) => category.id === categoryId,
    )?.title ?? FALLBACK_CATEGORY_KEY
  );
}

function getCategoryTitleById(categoryId: string, language: Language) {
  return (
    translations[language].home.categories.find(
      (category) => category.id === categoryId,
    )?.title ?? getCategoryKeyById(categoryId)
  );
}

function findCategoryIdBySlug(categorySlug: string) {
  const normalizedSlug = slugifyCategoryTitle(categorySlug);
  const languages = Object.keys(translations) as Language[];

  for (const language of languages) {
    const matched = translations[language].home.categories.find(
      (category) => slugifyCategoryTitle(category.title) === normalizedSlug,
    );

    if (matched) {
      return matched.id;
    }
  }

  return undefined;
}

function buildDescription(record: RawDictionaryRecord) {
  if (!record.def_citation) {
    return record.definition;
  }
  return `${record.definition} - ${record.def_citation}`;
}

function buildExample(record: RawDictionaryRecord) {
  const sourceParts: string[] = [];

  if (record.ex_source) {
    sourceParts.push(record.ex_source);
  }

  if (record.ex_date) {
    sourceParts.push(record.ex_date);
  }

  const sourceText = sourceParts.join(", ");
  const quoteText = record.ex_quote ? `"${record.ex_quote}"` : "";
  const analysisLabel = record.lang === "fr" ? "Analyse" : "Analisis";
  const analysisText = record.ex_analysis
    ? `${analysisLabel}: ${record.ex_analysis}`
    : "";

  if (sourceText && quoteText) {
    return analysisText
      ? `${sourceText}: ${quoteText} -> ${analysisText}`
      : `${sourceText}: ${quoteText}`;
  }

  if (quoteText) {
    return analysisText ? `${quoteText} -> ${analysisText}` : quoteText;
  }

  if (sourceText) {
    return analysisText ? `${sourceText} -> ${analysisText}` : sourceText;
  }

  return analysisText;
}

function mapRecordToItem(record: RawDictionaryRecord): DictionaryItem {
  return {
    name: record.term,
    name_norm: record.term_norm.toLowerCase(),
    desc: buildDescription(record),
    example: buildExample(record),
  };
}

export function getCategoryItems(categoryKey: string, language: Language) {
  const targetLang = mapLanguage(language);

  return Data.filter(
    (record) => record.category === categoryKey && record.lang === targetLang,
  )
    .sort((a, b) => a.seq_no - b.seq_no)
    .map(mapRecordToItem);
}

export function getCategorySlug(title: string) {
  return slugifyCategoryTitle(title);
}

export type ResolvedCategory = {
  id: string;
  key: string;
  title: string;
  items: DictionaryItem[];
  isFallback: boolean;
};

export function resolveCategoryFromSlug(
  categorySlug: string | undefined,
  language: Language,
): ResolvedCategory {
  const requestedId = categorySlug
    ? findCategoryIdBySlug(categorySlug)
    : undefined;
  const resolvedId = requestedId ?? FALLBACK_CATEGORY_ID;
  const resolvedKey = getCategoryKeyById(resolvedId);
  const resolvedTitle = getCategoryTitleById(resolvedId, language);
  const resolvedItems = getCategoryItems(resolvedKey, language);

  if (resolvedItems.length === 0 && resolvedId !== FALLBACK_CATEGORY_ID) {
    const fallbackTitle = getCategoryTitleById(FALLBACK_CATEGORY_ID, language);
    return {
      id: FALLBACK_CATEGORY_ID,
      key: FALLBACK_CATEGORY_KEY,
      title: fallbackTitle,
      items: getCategoryItems(FALLBACK_CATEGORY_KEY, language),
      isFallback: true,
    };
  }

  return {
    id: resolvedId,
    key: resolvedKey,
    title: resolvedTitle,
    items: resolvedItems,
    isFallback: resolvedId !== requestedId,
  };
}
